### PR TITLE
Basic housekeeping before Korean translation

### PR DESCRIPTION
**Pull request by simnalamburt**
Hi, my name is Hyeon Kim. And I translated this game in Korean with @xnuk. But before making a PR about Korean translation, we found that this game is currently not able to be run properly under CJK environment. So I'm hereby sending a basic housekeeping PR beforehand.

1.  Strip trailing whitespaces

    Trailing whitespaces are redundant and causes meaningless diffs with some editors. Removing it.

2.  Add line feed at the end of files

    By the [POSIX standard][psx], all text files should contain "newline" at the end of file. Adding it.

    ###### References
    1. [Answer of *"Why should text files end with a newline?"* question](http://stackoverflow.com/a/729795)
    2. [POSIX standard document][psx]

3.  Add [`<!DOCTYPE html>`][docstring] in front of the page

    Since this game uses WebGL and `<canvas>`, the index.html should be declared as a HTML5 document 
but it does not. Explicitly specifying it by adding [docstring] in front of the index.html

4.  Add an [`.editorconfig`][ecfg] file

    [EditorConfig][ecfg] helps developers define and maintain consistent coding styles between different editors and IDEs. See <http://editorconfig.org> for the further information

5.  Specify `index.html`'s encoding as UTF-8

    Currently index.html does not have `<meta charset>` tag. It will prevent CJK users from seeing their own language properly. We need it.

6.  Remove BOM

    The Unicode Standard permits the BOM in UTF-8, but does not require or recommend its use. Byte order has no meaning in UTF-8. Removing it.

    ###### Reference
    - https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8

7.  Unify the indentation

    The indentation rules in the source code were mixed with tabs and spaces * 4. Unifying it with tabs.

[psx]: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
[docstring]: https://en.wikipedia.org/wiki/Docstring
[ecfg]: http://editorconfig.org/

### CODE REVIEW

**Comment by simnalamburt** [comment]
I have finished the Korean translation.

- Play: https://game.hyeon.me/wbwwb/
- Source code: https://github.com/simnalamburt/wbwwb-kr

**Comment by terales** [comment]
@simnalamburt How do you think, is it necessary to translate a title of the page?
It might be good for a local SEO, but may be it have some drawbacks?

**Comment by simnalamburt** [comment]
@terales I did not translate the title of this game. I remained its title as "WE BECOME WHAT WE BEHOLD" at both [`<title>`](https://github.com/simnalamburt/wbwwb-ko/blob/master/index.html#L5) and [in-game](https://game.hyeon.me/wbwwb/). I also left the banner of this game untranslated in [README](https://github.com/simnalamburt/wbwwb-ko/blob/master/README.md).

But I translated the main quotation of this game (which is same with the title of this game) and decided to show it in README too, since I was quite sure that a few Korean *will* don't understand both the title of this game and what this game is going to state. I don't have any drawbacks that comes to mind. If you tell me one then I'll consider about it.

I updated the README not to show the translated quotation as if it were the title of this game.

**Comment by terales** [comment]
@simnalamburt thanks for you point of view! I'm thinking about localization into Russian and Ukrainian and just looking for existing solutions. Much appreciate your work!

The only drawback I see about untranslated title is connected with sharing experience and search snippet.

This is how localized page will be shared on facebook:
image

This is how page might be visible in Google search results:
image

My main concern is whether click-through rate for a link with with non-localized anchor is important or it's something we shouldn't care.

**Comment by ncase** [comment]
Thank you for doing this translation! I've linked your translated game at the bottom of the itch.io game page:

image

and I tweeted it out, if you didn't already see it: https://twitter.com/ncasenmare/status/816006169693212673

Many thanks again, @simnalamburt!

**Comment by simnalamburt** [comment]
@ncase Your welcome! I translated this game in order to deliver your message also to the Korean people who don't understand English. I just modified the very shell of this game, and the core essence of this game wouldn't be exist without you. Thank you for making this game.

@terales Oops thank you for the google search result. I just [edited the title](https://github.com/simnalamburt/wbwwb-ko/commit/e7a9b6a2d0ca30e1932f85d6194d1f9af6f41d3a).

The main reason that I did not translated the title of this game is that most foreign which imported into Korea is release with its title untranslated. I don't know who started this practice and why this practice is started, but I just decided to stick to the Korean localization practice.

  

> These games are imported into Korea with its title untranslated.

I don't have any knowledge about Russian and Ukrainian game industry practice. If your people are familiar with translated title, I think it'd be better to translate this game's title too!

**Pull request closed without merging**
