### PR TITLE
Display dynamic text objects instead of baking text into assets

### PR DESCRIPTION
**Pull request by stefanlesser**
This pull request removes text that was baked into assets and displays dynamic text objects instead. This will be helpful when translating the game into other languages.
I'm not proud of the repetitive code, and for sure this could be refactored into much leaner code, but I've never used PIXI before, and this does the trick. ;-)

Note: The `Post_Post_Credits` scene with the social buttons still uses text in assets. This is a bit trickier to change than it was in all other cases.

Some assets are also no longer necessary (in the `Quote` and `Credits` scenes), because removing the text made them empty, transparent images. I've still kept the images, and the references in the code to them. It would probably be good to remove the assets completely.

### CODE REVIEW

**Comment by stefanlesser** [comment]
Oh, and my work of editing the assets is pretty crappy, too… the preload background in particular. Sorry, only had Preview to do it.

**Comment by ncase** [comment]
Thank you again for doing all this! I'm currently finishing up my next interactive project (it's about alternative voting systems) but once I've finished it (by next week), I'll pull all this, and have a German version of WBWWB live somewhere! (As well as a new repo for others who want to help translate it) Many thanks again!

**Comment by terales** [comment]
@ncase can you announce new repository in this on or on your blog? I want to translate it into Russian.

**Comment by ncase** [comment]
@terales: I'll announce it here on this repo! (and also on [my Twitter](@ncasenmare)) Thank you!

**Pull request merged**
